version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: app
    ports:
      - 5432:5432

  api:
    build: .
    restart: always
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - .:/usr/src/app/